### ISSUE TITLE
Add weight to parent plan

### ISSUE THREAD

**Issue by denismitr** [tmyers273/laravel-stripe-billing#9]
Since parent plans do not contain price, there is currently no way to sort them according to priviledges they give

**Comment by denismitr** [comment]
This is done. Now I would like a `scopeWeighted()` scope method to display plans with less weight first. E.g. base, pro, gold

**Comment by tmyers273** [comment]
Is there a convention for which plan is the "better" one? In other words, is a higher weight a better plan?

Would a `weight` of 1 correspond with a cheap plan? And a `weight` of 10 a more expensive plan?

**Comment by denismitr** [comment]
Yes, the bigger is the weight value the better is the plan. I'll add that to the docs
